name: MySQL Setup in GitHub Actions

on:
  push:
    branches:
      - master

env:
  MYSQL_DATABASE:  ${{ secrets.ECOM_DB }}
  MYSQL_USER: ${{ secrets.ECOM_DB_USERNAME }}
  MYSQL_PASSWORD: ${{ secrets.ECOM_DB_PASSWORD }}

jobs:
  mysql-setup:
    runs-on: ubuntu-latest  # This is the environment where the MySQL service will be installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Wait for MySQL to start
        run: |
          # Wait until MySQL service is available before executing further commands
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL to start..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Setup MySQL 
        run: |
            sudo systemctl start mysql
            mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' \
              -u${{ secrets.MASTER_MYSQL_USERNAME }} \
              -p${{ secrets.MASTER_MYSQL_PASSWORD }}

            mysql -e "CREATE USER '${{ env.MYSQL_USER }}'@'localhost' \
              IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';" \
              -u${{ secrets.MASTER_MYSQL_USERNAME }} \
              -p${{ secrets.MASTER_MYSQL_PASSWORD }}

            mysql -e "GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, DROP, CREATE, TRUNCATE \
              ON ${{ env.MYSQL_DATABASE }}.* TO '${{ env.MYSQL_USER }}'@'localhost' \
              WITH GRANT OPTION;" \
              -u${{ secrets.MASTER_MYSQL_USERNAME }} \
              -p${{ secrets.MASTER_MYSQL_PASSWORD }}

            mysql -e "FLUSH PRIVILEGES;" \
              -u${{ secrets.MASTER_MYSQL_USERNAME }} \
              -p${{ secrets.MASTER_MYSQL_PASSWORD }}


      - name: Test MySQL Connection
        run: |
          mysql -u shahzaib -p123 -h 127.0.0.1 -e "SHOW DATABASES;"

      - name: Run your tests or database commands
        run: |
          # Replace this with the command you want to run, such as running your PHP tests
          mysql -u ${{ secrets.ECOM_DB_USERNAME }} -p${{ secrets.ECOM_DB_PASSWORD }} -h 127.0.0.1 -e "SHOW DATABASES;"
