
name: MySQL Setup in GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  mysql-setup:
    runs-on: ubuntu-latest  # This is the environment where the MySQL service will be installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Set up MySQL user and privileges
        run: |
          sudo /etc/init.d/mysql start
           mysql -e 'CREATE DATABASE learn_vern' -u${{ secrets.ECOM_DB_USERNAME }} -p${{ secrets.ECOM_DB_PASSWORD }};




      - name: Test MySQL Connection
        run: |
          mysql -u shahzaib -p123 -h  - 33306:3306 -e "SHOW DATABASES;"

      - name: Run your tests or database commands
        run: |
          # Replace this with the command you want to run, such as running your PHP tests
          mysql -u ${{secrets.ECOM_DB_USERNAME}} -p${{secrets.ECOM_DB_PASSWORD}} -h  - 33306:3306 -e "SHOW DATABASES;"

