name: Laravel CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Set up PHP with the specified version
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.12'
          extensions: mbstring, bcmath, pdo_mysql

      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Copy the environment file
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Install PHP dependencies via Composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-scripts --no-progress

      # Generate the application key
      - name: Generate application key
        run: php artisan key:generate

      # Set proper directory permissions
      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # Configure MySQL database
      - name: Set up MySQL database
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: learn_vern
          DB_USERNAME: root
          DB_PASSWORD: 123
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          mysql -u root --password=123 -e "CREATE DATABASE IF NOT EXISTS learn_vern;"
          mysql -u root --password=123 -e "ALTER USER 'root'@'localhost'; FLUSH PRIVILEGES;"
          mysql -u root --password=123 -e "GRANT ALL PRIVILEGES ON learn_vern.* TO 'root'@'localhost';"
          mysql -u root --password=123 -e "FLUSH PRIVILEGES;"

      # Debug MySQL Authentication
      - name: Debug MySQL Authentication
        run: |
          mysql -u root --password="" -e "SELECT USER(), CURRENT_USER();" || echo "Authentication failed."

      # Configure Laravel .env file
      - name: Configure Laravel .env
        run: |
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=learn_vern/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=/' .env

      # Run Laravel migrations
      - name: Run migrations
        run: php artisan migrate --force

      # Run Laravel tests
      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: learn_vern
          DB_USERNAME: root
          DB_PASSWORD: ""
        run: php artisan test
