name: Laravel CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Set up PHP with the specified version
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Copy the environment file
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Install PHP dependencies via Composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-scripts --no-progress

      # Generate the application key
      - name: Generate application key
        run: php artisan key:generate

      # Set proper directory permissions
      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # Configure MySQL database
      - name: Set up MySQL database
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS test_db;"
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'secret'; FLUSH PRIVILEGES;"

      # Run Laravel tests
      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: secret
        run: php artisan test
