name: Laravel CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server

    - name: Start MySQL Service
      run: sudo service mysql start

    - name: Set Up MySQL Database
      run: |
        sudo mysql -e "CREATE USER IF NOT EXISTS 'shahzaib'@'localhost' IDENTIFIED BY '123';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'shahzaib'@'localhost' WITH GRANT OPTION;"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, bcmath, soap, zip, curl

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Update .env for GitHub Actions
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=learn_vern" >> .env
        echo "DB_USERNAME=shahzaib" >> .env  # Use the new user 'shahzaib'
        echo "DB_PASSWORD=123" >> .env      # Use the password '123'

    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 --silent; then
            echo "MySQL is ready!";
            break;
          fi
          echo "Waiting for MySQL to be ready...";
          sleep 3;
        done

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test
